name: prediction_app
description: A new Flutter project
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
repository: https://github.com/rrousselGit/provider
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  in_app_purchase: ^0.5.2
  flutter_screenutil: ^5.0.0+2
  outline_gradient_button: ^2.0.0+1
  percent_indicator: ^3.0.1
  flutter_spinkit: ^5.1.0
  syncfusion_flutter_sliders: ^19.2.62
  #flutter_xlider: ^3.4.0
  fluttertoast: ^8.0.8
  page_transition: ^2.0.2
  flutter_staggered_animations: "^1.0.0"
  flutter_svg: ^0.22.0
  animated_text_kit: ^4.2.1
  provider: ^6.0.1
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.0
  build_runner: ^2.1.2
  flutter_easyloading: ^3.0.3
  sigv4: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-VariableFont_wght.ttf
